---
  apiVersion: v1
  kind: Service
  metadata:
    name: hello-node
    labels:
      app: hello-node
  spec:
    ports:
    - port: 9080
      name: http
    selector:
      app: hello-node
---
  apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: hello-node-deployment
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: hello-node
          version: v1
      spec:
        containers:
        - name: hello-node
          image: gcr.io/amp-istio/hello-node-image:v1
          ports:
          - containerPort: 9080
---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: gateway
    annotations:
      kubernetes.io/ingress.class: "istio"
  spec:
    rules:
    - http:
        paths:
        - path: /.*
          backend:
            serviceName: hello-node
            servicePort: 9080
